name: CI with Pip Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python with cached dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # This automatically handles caching of pip packages
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        # Replace this with your actual test command
        run: python -m unittest discover
