name: CI with Cache Priming

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        id: cache-deps # Give the step an ID to reference its output
        uses: actions/cache@v4
        with:
          # The directory to cache
          path: node_modules
          # The specific key you requested
          key: cache-dd4245f

      - name: prime-cache-dd4245f
        run: echo "The cache-hit property is: ${{ steps.cache-deps.outputs.cache-hit }}"

      - name: Install dependencies if cache missed
        # This is the crucial step: only run 'npm install' if the cache was not restored.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install html-lint

      - name: Lint HTML file
        run: npx html-lint index.html
